8[package]
name = "relay_cli"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "CLI testing tool for RelayHub core library"
repository = "https://github.com/ninja-left/relay-hub"

[dependencies]
relay_core = { path = "../core" }
