## Additional Context
Any extra info or references.

name: 🌱 Feature
description: Suggest a feature/enhancement
title: "[FEATURE] <title>"
labels: ["enhancement"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing suggestion/issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Feature description
    description: A clear and concise description of what you’d like to see or be added.
  validations:
    required: true
- type: textarea
  attributes:
    label: Reason
    description: Why is this feature valuable to you or the project?
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives
    description: Is there an alternative tool available or method to implement this?
    placeholder: |
      Tool X exists, It can be implemented using Y, ...
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Context
    description: |
      If it solves an issue, you can reference the affected issues here.

      Tip: You can attach images or other files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
