name: Auto Format

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run cargo fmt
        run: cargo fmt --all
        working-directory: /relay-hub/core/

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -u
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-format code"
            git push
          fi
