name: Rust CI

on:
  workflow_run:
    workflows: ["Auto Format"]
    types:
      - completed

jobs:
  build:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            core/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('core/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Format check
        working-directory: core
        run: cargo fmt --all -- --check

      - name: Clippy
        working-directory: core
        run: cargo clippy --all-targets -- -D warnings

      - name: Build
        working-directory: core
        run: cargo build --all --verbose

      - name: Test
        working-directory: core
        run: cargo test --all --verbose
